=== AlexRogalskiy/chaostoolkit/chaostoolkit/plan-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "properties": {
      "backend": {
        "id": "/properties/backend",
        "properties": {
          "name": {
            "description": "The name of the backend to load and use to run probes and actions. Supported backends are \"kubernetes\" and \"noop\". The latter is handy when running dry runs. You can also supply a Python module or package dotted path of your own backend provided it implements the necessary probes and/or actions.",
            "title": "The backend name schema",
            "type": "string"
          }
        },
        "type": "object"
      },
      "description": {
        "description": "A description of the plan to execute",
        "title": "The plan description schema",
        "type": "string"
      },
      "method": {
        "items": {
          "properties": {
            "action": {
                "properties": {
                    "parameters": {
                        "description": "A mapping of parameters to provide the action with as-is",
                        "title": "The action parameters schema",
                        "type": "object"
                    },
                    "pauses": {
                        "description": "Should the process wait before and/or after the action",
                        "title": "The pause parameters schema",
                        "type": "object",
                        "properties": {
                            "before": {
                                "type": "number",
                                "default": 0,
                                "description": "How long to wait before triggering the action"
                            },
                            "after": {
                                "type": "number",
                                "default": 0,
                                "description": "How long to wait after triggering the action"
                            }
                        }
                    }
                }
            },
            "probes": {
              "properties": {
                "steady": {
                  "properties": {
                    "name": {
                      "default": "",
                      "description": "The name of the steady probe that should be applied",
                      "title": "The steady probe name schema",
                      "type": "string"
                    }
                  },
                  "required": [
                    "name"
                  ],
                  "type": "object"
                },
                "close": {
                    "properties": {
                      "name": {
                        "default": "",
                        "description": "The name of the close probe that should be applied",
                        "title": "The close probe name schema",
                        "type": "string"
                      }
                    },
                    "required": [
                      "name"
                    ],
                    "type": "object"
                  }
              },
              "type": "object"
            },
            "title": {
              "description": "A user-friendly title for this probe.",
              "title": "The probe title schema",
              "type": "string"
            }
          },
          "type": "object"
        },
        "minItems": 0,
        "type": "array"
      },
      "title": {
        "description": "A user-frendly title of the plan to execute.",
        "title": "The plan title schema",
        "type": "string"
      }
    },
    "required": [
      "method"
    ],
    "type": "object"
  }

=== AlexRogalskiy/chaostoolkit/tests/kill-restart-microservice.json
{
    "title": "Kill a microservice",
    "description": "Killing a microservice will trigger service failure",
    "backend": {
        "name": "kubernetes"
    },
    "method": [
        {
            "title": "Checking our system is healthy",
            "probes": {
                "steady": {
                    "name": "microservices-all-healthy"
                }
            }
        },
        {
            "title": "Killing a service abruptly",
            "action": {
                "name": "kill-microservice",
                "parameters": {
                    "name": "cherrypy-webapp"
                },
                "pauses": {
                    "after": 5
                }
            },
            "probes": {
                "steady": {
                    "name": "microservice-available-and-healthy",
                    "parameters": {
                        "name": "cherrypy-webapp"
                    }
                },
                "close": {
                    "name": "microservice-is-not-available",
                    "parameters": {
                        "name": "cherrypy-webapp"
                    }
                }
            }
        },
        {
            "title": "Start a microservice",
            "action": {
                "name": "start-microservice",
                "parameters": {
                    "config-path": "/home/sylvain/dev/oss/weavcfg/cherrypy-webapp.json"
                },
                "pauses": {
                    "after": 5
                }
            },
            "probes": {
                "steady": {
                    "name": "microservice-is-not-available",
                    "parameters": {
                        "name": "cherrypy-webapp"
                    }
                },
                "close": {
                    "name": "microservice-available-and-healthy",
                    "parameters": {
                        "name": "cherrypy-webapp"
                    }
                }
            }
        },
        {
            "title": "Checking our system is healthy once microservice has been restarted",
            "probes": {
                "steady": {
                    "name": "microservices-all-healthy"
                }
            }
        }
    ]
}
